package com.example.stock;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.app.ProgressDialog;
import android.content.DialogInterface;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import java.util.ArrayList;


// Written by Cade Cottrell for CS4301.002, Stock Assignment
// netid: cac160030


// Main Activity, shows main activity on screen...
// has the editText, find button and recyclerview
public class MainActivity extends AppCompatActivity {

    Button find;
    TextView debug;
    EditText stockLookup;
    StockFinder stockFinder;
    RecyclerViewAdapter adapter;

    //autogenerated onCreate
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        find = findViewById(R.id.findButton);
        debug = findViewById(R.id.debug);
        stockLookup = findViewById(R.id.stockLookup);

    }


    // OnClick button to find stock user typed, if it exists
    // helps fill the recyclerview
    public void findButtonOnClick(View view)
    {
        String stock = stockLookup.getText().toString().toUpperCase();

        String urlString = "https://personal.utdallas.edu/~John.Cole/2017Spring/"+ stock +".txt";


        ViewGroup viewGroup = (ViewGroup) ((ViewGroup) this.findViewById(android.R.id.content)).getChildAt(0);
        stockFinder = new StockFinder(this, viewGroup, adapter);

        stockFinder.execute(urlString);
    }



}
